[masters]
yeet-01 ansible_host=10.42.10.100

[workers]
yeet-02 ansible_host=10.42.10.101
yeet-03 ansible_host=10.42.10.102

[fleet:children]
masters
workers

[fleet:vars]
ansible_user=icd
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
nomad_server=yeet-01
nomad_server_ip=10.42.10.100
nomad_version=1.9.4
openshell_version=0.0.13
